spring:
  application:
    name: coordinator
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5
          temperature: 1
    mcp:
      client:
        name: coordinator
        request-timeout: 30s
        type: async
        sse:
          connections:
            project-manager-agent:
              url: ${PM_MCP_SERVER_URL:http://localhost:9091}
              sse-endpoint: /api/v1/sse
            documentation-agent:
              url: ${DOCUMENTATION_AGENT_MCP_SERVER_URL:http://localhost:9095}
              sse-endpoint: /api/v1/sse
      server:
        name: coordinator
        instructions: Coordinate between various MCP servers to fulfill requests efficiently.
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp/message

server:
  port: ${SERVER_PORT:9099}

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: coordinator